
server:
  port: 10010
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: rootroot
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
    driver-class-name: org.gjt.mm.mysql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1 #将访问ip定在本地，否则有可能找不到生产者
    instance-id: ${spring.application.name}:${server.port}

zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/** # 将数据微服务映射到/item/**内